mod sub_folder;
use sub_folder::failure::handle_failure;

fn main() {
    handle_failure();
}
